name: evaranshark_weathercast
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  another_flutter_splash_screen: ^1.1.4
  async_button_builder: ^3.0.0+1
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  email_validator: ^2.1.17
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  geolocator: ^9.0.2
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.0
  pixel_snap: ^0.1.2
  provider: ^6.0.5
  system_settings: 
    git:
      url: https://github.com/evaranshark/system_settings.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/icon_google_color.svg
    - assets/images/eye.svg
    - assets/images/eye-off.svg
    - assets/images/rain_big.png
    - assets/images/slight_rain_big.png
    - assets/images/snow_big.png
    - assets/images/sun_big.png
    - assets/images/sunny_rain_big.png
    - assets/images/thunder_big.png
    - assets/images/thunder_sm.png
    - assets/images/Sun_sm.png
    - assets/images/CloudMoon_sm.png
    - assets/images/CloudRain_sm.png
    - assets/images/CloudSnow_sm.png
    - assets/images/CloudSun_sm.png
    - assets/images/Wind.svg
    - assets/images/Drop.svg
