// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczuf0JFttIaJQ1A63QCsalVjQ0z8sgfQ',
    appId: '1:354479704196:web:d932d4845316f16c535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    authDomain: 'evaranshark-test-apps.firebaseapp.com',
    storageBucket: 'evaranshark-test-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZIYLoeTpeonqvO0U-A6ATa_8pPu-7us',
    appId: '1:354479704196:android:14d03dafa445be19535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    storageBucket: 'evaranshark-test-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGqHRARBw8axpQC3yUA7GxGdxrzCtrlj4',
    appId: '1:354479704196:ios:a14ed3bd4f95aa3d535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    storageBucket: 'evaranshark-test-apps.appspot.com',
    iosClientId: '354479704196-l5gep022p72mlc9gn02u6g301fgmrok9.apps.googleusercontent.com',
    iosBundleId: 'com.example.evaransharkWeathercast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGqHRARBw8axpQC3yUA7GxGdxrzCtrlj4',
    appId: '1:354479704196:ios:e464dd5d1d00fd73535ad1',
    messagingSenderId: '354479704196',
    projectId: 'evaranshark-test-apps',
    storageBucket: 'evaranshark-test-apps.appspot.com',
    iosClientId: '354479704196-kmh906lesja2rehci6lre57ot5a1fhcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.evaransharkWeathercast.RunnerTests',
  );
}
